{
  "swagger": "2.0",
  "info": {
    "description": "This is documentation for FlexxWare API from Soluvine GmbH.  You can find out more about Soluvine solutions at [https://soluvine.com/flexxlink](https://soluvine.com/flexxlink).  </br> The FlexxWare API is using REST API to define its endpoints. This page also provides sample Authorization information and sample responses to each API endpoint.",
    "version": "1.2.0",
    "title": "FlexxWare for Dynamics 365 Finance and Operations",
    "termsOfService": "https://soluvine.com/",
    "contact": {
      "email": "flexx@soluvine.com"
    },
    "license": {
      "name": "Soluvine GmbH",
      "url": "https://soluvine.com/flexxlink/"
    }
  },
  "host": "yourcloudd365aos.axcloud.dynamics.com",
  "basePath": "/api/services/",
  "tags": [
    {
      "name": "EDI and B2B interfaces",
      "description": "Endpoints to integrate EDI messages into D365 F&O.",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://soluvine.com/"
      }
    },
    {
      "name": "OCR Vendor invoice",
      "description": "Endpoint to integrate data from OCR invoices.",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://soluvine.com/flexxstore/"
      }
    },
    {
      "name": "Document archive",
      "description": "Endpoint to archive documents in D365 F&O.",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://soluvine.com/flexxstore/"
      }
    },
    {
      "name": "BVBS interface",
      "description": "Imports BVBS (Bundesvereinigung Bausoftware) data into D365 F&O",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://soluvine.com/"
      }
    },
    {
      "name": "Production interfaces",
      "description": "Imports Production data into D365 F&O",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://soluvine.com/"
      }
    },
    {
      "name": "Warehouse interfaces",
      "description": "Imports warehouse data into D365 F&O",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://soluvine.com/"
      }
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/FXLInboundServices_B2B/FXLSalesTableService/createSalesTable": {
      "post": {
        "tags": [
          "EDI and B2B interfaces"
        ],
        "summary": "Upload a sales order",
        "description": "",
        "operationId": "createSalesTable",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "A new sales order.",
            "schema": {
              "$ref": "#/definitions/SalesOrderCreate"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_B2B/FXLSalesTableService/updateSalesTable": {
      "post": {
        "tags": [
          "EDI and B2B interfaces"
        ],
        "summary": "Update a sales order",
        "description": "",
        "operationId": "updateFile",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "An update of a sales order.",
            "schema": {
              "$ref": "#/definitions/SalesOrderUpdate"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_B2B/FXLPurchTableService/createPurchTable": {
      "post": {
        "tags": [
          "EDI and B2B interfaces"
        ],
        "summary": "Create a purchase order",
        "description": "",
        "operationId": "createPurchTable",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "A new purchase order.",
            "schema": {
              "$ref": "#/definitions/PurchaseOrderCreate"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_B2B/FXLPurchTableService/confirmPurchTable": {
      "post": {
        "tags": [
          "EDI and B2B interfaces"
        ],
        "summary": "Confirm a purchase order",
        "description": "",
        "operationId": "confirmPurchTable",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "A confimation of a purchase order.",
            "schema": {
              "$ref": "#/definitions/PurchaseOrderConfirm"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_B2B/FXLPurchTableService/invoicePurchTable": {
      "post": {
        "tags": [
          "EDI and B2B interfaces"
        ],
        "summary": "Create a purchase invoice",
        "description": "",
        "operationId": "invoicePurchTable",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "An invoice for a purchase order.",
            "schema": {
              "$ref": "#/definitions/InvoicePurchTable"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_OCR/FXLVendInvoiceService/createVendInvoice": {
      "post": {
        "tags": [
          "OCR Vendor invoice"
        ],
        "summary": "Create a vendor invoice",
        "description": "",
        "operationId": "createVendInvoice",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "An invoice for a purchase order.",
            "schema": {
              "$ref": "#/definitions/CreateVendInvoice"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_B2B/FXLCustCollectionService/confirmCollection": {
      "post": {
        "tags": [
          "EDI and B2B interfaces"
        ],
        "summary": "Confirm a customer collection",
        "description": "",
        "operationId": "confirmCollection",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "An invoice for a purchase order.",
            "schema": {
              "$ref": "#/definitions/ConfirmCollection"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/FXLInboundServicesDoc/FXLDocArchiveService/createDocArchiveRef": {
      "post": {
        "deprecated": true,
        "tags": [
          "Document archive"
        ],
        "summary": "Create document archive entry",
        "description": "",
        "operationId": "createDocArchiveRef",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "An entry in the document archive.",
            "schema": {
              "$ref": "#/definitions/CreateDocuArchiveRef"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXSInboundServices/FXSDocArchiveService/createDocArchiveRef": {
      "post": {
        "tags": [
          "Document archive"
        ],
        "summary": "Create document archive entry",
        "description": "",
        "operationId": "createDocArchiveRefFXS",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "An entry in the document archive.",
            "schema": {
              "$ref": "#/definitions/CreateDocuArchiveRefFXS"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/BVBSFileImportServiceGroup/FXLBVBSImportFileService/importBVBSFile": {
      "post": {
        "tags": [
          "BVBS interface"
        ],
        "summary": "Imports a set of BVBS data",
        "description": "",
        "operationId": "importBVBSFile",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "A set of BVBS data.",
            "schema": {
              "$ref": "#/definitions/BvbsImport"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_Prod/FXLProdTableService/start": {
      "post": {
        "tags": [
          "Production interfaces"
        ],
        "summary": "Reports a Production order is started",
        "description": "",
        "operationId": "start",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Start Production Order in D365 F&O.",
            "schema": {
              "$ref": "#/definitions/ProductionStart"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_Prod/FXLProdTableService/reportAsFinishedProgress": {
      "post": {
        "tags": [
          "Production interfaces"
        ],
        "summary": "Reports progress of a Production order",
        "description": "",
        "operationId": "reportAsFinishedProgress",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Progress of a Production Order in D365 F&O.",
            "schema": {
              "$ref": "#/definitions/ProductionProgress"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_Prod/FXLProdTableService/reportAsFinishedCompleted": {
      "post": {
        "tags": [
          "Production interfaces"
        ],
        "summary": "Reports a Production order is finished",
        "description": "",
        "operationId": "reportAsFinishedCompleted",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Finish Production Order in D365 F&O.",
            "schema": {
              "$ref": "#/definitions/ProductionFinished"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_WMS/FXLWMSJournalService/createWMSJournal": {
      "post": {
        "tags": [
          "Warehouse interfaces"
        ],
        "summary": "Creates item arrival journal",
        "description": "",
        "operationId": "createWMSJournal",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Create item arrival journal in D365 F&O.",
            "schema": {
              "$ref": "#/definitions/ItemArrivalCreate"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/FXLInboundServices_WMS/FXLWMSPickingRegistrationService/registerPickList": {
      "post": {
        "tags": [
          "Warehouse interfaces"
        ],
        "summary": "Registers a picking list",
        "description": "",
        "operationId": "registerPickList",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Register picking list in D365 F&O.",
            "schema": {
              "$ref": "#/definitions/PickingListRegistration"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          },
          "400": {
            "description": "bad request structure",
            "schema": {
              "$ref": "#/definitions/Api400Response"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    }
  },
  "definitions": {
    "CreateDocuArchiveRef": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "accountType": {
              "type": "string",
              "description": "Vendor or Customer"
            },
            "agreementId": {
              "type": "string"
            },
            "archiveId": {
              "type": "string"
            },
            "barcodeId": {
              "type": "string"
            },
            "custVendAccount": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "documentCreatedDateTime": {
              "type": "string",
              "format": "date-time"
            },
            "documentDate": {
              "type": "string",
              "format": "date"
            },
            "documentId": {
              "type": "string"
            },
            "fileData": {
              "type": "string",
              "description": "base64 encoded file contents"
            },
            "fileId": {
              "type": "string",
              "format": "uuid"
            },
            "fileName": {
              "type": "string"
            },
            "filePath": {
              "type": "string"
            },
            "fileUrl": {
              "type": "string"
            },
            "id": {
              "type": "string",
              "format": "uuid"
            },
            "inventBatchId": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "orderId": {
              "type": "string"
            },
            "orderRefId": {
              "type": "string"
            },
            "orderType": {
              "type": "string"
            },
            "projId": {
              "type": "string"
            },
            "quotationId": {
              "type": "string"
            },
            "refJournalId": {
              "type": "string"
            },
            "trader": {
              "type": "integer"
            }
          }
        }
      }
    },
    "CreateDocuArchiveRefFXS": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "companyId": {
              "type": "string"
            },
            "fileData": {
              "type": "string",
              "description": "base64 encoded file contents"
            },
            "docArchive": {
              "type": "object",
              "properties": {
                "description": {
                  "type": "string"
                },
                "externalDocTypeId": {
                  "type": "string",
                  "enum": [
                    "Purch invoice",
                    "VALUE2",
                    "VALUEN"
                  ]
                }
              }
            },
            "docArchiveRef": {
              "type": "object",
              "properties": {
                "accountTypestr": {
                  "type": "string",
                  "description": "Vendor or Customer",
                  "enum": [
                    "Vend",
                    "Cust",
                    "None"
                  ]
                },
                "agreementId": {
                  "type": "string"
                },
                "barcodeId": {
                  "type": "string",
                  "description": "Dedicated to barcode handling. If barcode is sent, the following values are taken from D365 only: accountTypestr, custVendAccount, orderTypeStr, orderId, agreementId, documentDate, documentId, inventBatchId, projId, quotationId, assetId."
                },
                "custVendAccount": {
                  "type": "string"
                },
                "documentCreatedDateTime": {
                  "type": "string",
                  "format": "date-time"
                },
                "documentDate": {
                  "type": "string",
                  "format": "date"
                },
                "documentId": {
                  "type": "string"
                },
                "fileId": {
                  "type": "string",
                  "format": "uuid"
                },
                "fileName": {
                  "type": "string"
                },
                "filePath": {
                  "type": "string"
                },
                "fileUrl": {
                  "type": "string"
                },
                "inventBatchId": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "orderTypeStr": {
                  "type": "string",
                  "enum": [
                    "None",
                    "PurchOrder",
                    "PurchAgreement",
                    "SalesOrder",
                    "SalesAgreement",
                    "SalesQuotation",
                    "TransferOrder",
                    "WMSJournalTable",
                    "CustCollectionLetter"
                  ]
                },
                "projId": {
                  "type": "string"
                },
                "quotationId": {
                  "type": "string"
                },
                "assetId": {
                  "type": "string"
                },
                "trader": {
                  "type": "integer"
                },
                "connectionId": {
                  "type": "string",
                  "description": "Name of the connection as defined in D365. Used with the fileUrl value."
                }
              }
            }
          }
        }
      }
    },
    "CreateVendInvoice": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "companyId": {
              "type": "string"
            },
            "currencyCode": {
              "type": "string"
            },
            "documentDate": {
              "type": "string",
              "format": "date"
            },
            "documentId": {
              "type": "string",
              "description": "Internal FlexxLink document number."
            },
            "fileData": {
              "type": "string",
              "format": "byte",
              "description": "Base64 encoded document. Accepts PDF, MSG, TIFF, JPG."
            },
            "fileName": {
              "type": "string"
            },
            "iBAN": {
              "type": "string"
            },
            "invoiceAccount": {
              "type": "string"
            },
            "invoiceAmount": {
              "type": "number",
              "description": "Precision of two decimals."
            },
            "num": {
              "type": "string",
              "description": "Invoice number."
            },
            "orderAccount": {
              "type": "string"
            },
            "purchId": {
              "type": "string"
            },
            "purchName": {
              "type": "string"
            },
            "taxAmount": {
              "type": "number",
              "description": "Precision of two decimals"
            },
            "vATNum": {
              "type": "string"
            },
            "vendReference": {
              "type": "string"
            }
          }
        }
      }
    },
    "ConfirmCollection": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "header": {
              "$ref": "#/definitions/CollectionHeader"
            },
            "lines": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CollectionLines"
              }
            }
          }
        }
      }
    },
    "InvoicePurchTable": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "header": {
              "$ref": "#/definitions/PurchaseInvoiceHeader"
            },
            "lines": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/PurchaseInvoiceLine"
              }
            }
          }
        }
      }
    },
    "SalesOrderUpdate": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "header": {
              "$ref": "#/definitions/Header"
            },
            "lines": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Line"
              }
            }
          }
        }
      }
    },
    "SalesOrderCreate": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "header": {
              "$ref": "#/definitions/Header"
            },
            "lines": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Line"
              }
            }
          }
        }
      },
      "example": {
        "_contract": {
          "message": {
            "companyId": "usmf",
            "fromSystem": "Azure Integration",
            "description": "Test integration",
            "applicationId": "Backend System",
            "messageId": "abcd-1234-efgh-5678",
            "messageTimestamp": "YYYY-MM-DDTHH:mm:ss"
          },
          "header": {
            "barcode": "03294782374",
            "receiptDateRequested": "2022-04-12T00:00:00.000Z",
            "shippingDateRequested": "2022-05-25T00:00:00.000Z",
            "custAccount": "234987",
            "gLNCode": "4305615009999",
            "customerRef": "PO123456",
            "PurchOrderFormNum": "101183255",
            "currencyCode": "EUR",
            "deliveryName": "Warehouse No. 1",
            "deliveryCity": "Atlanta",
            "deliveryCountryRegionId": "Piedmont",
            "deliveryState": "Georgia",
            "deliveryStreet": "Everrest Street",
            "deliveryZipCode": "98122-US",
            "dlvMode": "Freight",
            "dlvTerm": "30 days",
            "salesType": "Sales",
            "shipComplete": true,
            "email": "test@testemail.com",
            "contactPersonName": "John Smith",
            "phone": "0932472834691",
            "notes": "Verification message",
            "lines": [
              {
                "lineNum": 1,
                "itemId": "4305615615318",
                "salesPrice": 10,
                "salesQty": 408,
                "salesUnit": "PCE",
                "itemBarCode": "4305615615318",
                "globalTradeItemNumber": "4305615615318",
                "name": "Contoso Item"
              },
              {
                "lineNum": 2,
                "itemId": "4305615616429",
                "salesPrice": 20,
                "salesQty": 30,
                "salesUnit": "PCE",
                "itemBarCode": "4305615616429",
                "globalTradeItemNumber": "4305615616429",
                "name": "Contoso Item"
              }
            ]
          }
        }
      }
    },
    "PurchaseOrderConfirm": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "header": {
              "$ref": "#/definitions/PurchaseConfirmHeader"
            },
            "lines": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/PurchaseConfirmLine"
              }
            }
          }
        }
      }
    },
    "Message": {
      "type": "object",
      "properties": {
        "applicationId": {
          "type": "string"
        },
        "companyId": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "messageId": {
          "type": "string"
        },
        "messageTimeStamp": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "Header": {
      "type": "object",
      "properties": {
        "barCode": {
          "type": "string"
        },
        "contactPersonName": {
          "type": "string"
        },
        "currencyCode": {
          "type": "string"
        },
        "custAccount": {
          "type": "string"
        },
        "customerRef": {
          "type": "string"
        },
        "deliveryAddress": {
          "type": "string",
          "format": "deprecated"
        },
        "gLNCode": {
          "type": "string"
        },
        "deliveryName": {
          "type": "string"
        },
        "deliveryCity": {
          "type": "string"
        },
        "deliveryCountryRegionId": {
          "type": "string"
        },
        "deliveryState": {
          "type": "string"
        },
        "deliveryStreet": {
          "type": "string"
        },
        "deliveryZipCode": {
          "type": "string"
        },
        "dlvMode": {
          "type": "string"
        },
        "dlvTerm": {
          "type": "string"
        },
        "salesType": {
          "type": "string"
        },
        "shipComplete": {
          "type": "boolean"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "purchOrderFormNum": {
          "type": "string"
        },
        "receiptDateRequested": {
          "type": "string"
        },
        "shippingDateRequested": {
          "type": "string"
        }
      }
    },
    "CollectionHeader": {
      "type": "object",
      "properties": {
        "barCode": {
          "type": "string"
        },
        "currencyCode": {
          "type": "string"
        },
        "custAccount": {
          "type": "string"
        },
        "fXLImportId": {
          "type": "string"
        },
        "gLNCode": {
          "type": "string"
        },
        "isCredit": {
          "type": "number"
        },
        "message": {
          "type": "string"
        },
        "paymMode": {
          "type": "string"
        },
        "paymReference": {
          "type": "string"
        },
        "receiverBankAccount": {
          "type": "string"
        },
        "receiverBankName": {
          "type": "string"
        },
        "receiverIBAN": {
          "type": "string"
        },
        "receiverSWIFTNo": {
          "type": "string"
        },
        "senderBankAccount": {
          "type": "string"
        },
        "senderBankName": {
          "type": "string"
        },
        "senderIBAN": {
          "type": "string"
        },
        "senderSWIFTNo": {
          "type": "string"
        },
        "settlementDate": {
          "type": "string",
          "format": "date-time"
        },
        "totalAmount": {
          "type": "number",
          "description": "Precision of two decimals."
        },
        "transDateTime": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "PurchaseOrderCreate": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "header": {
              "$ref": "#/definitions/PurchaseHeader"
            },
            "lines": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/PurchaseLine"
              }
            }
          }
        }
      }
    },
    "PurchaseInvoiceHeader": {
      "type": "object",
      "required": [
        "orderAccount",
        "documentNum"
      ],
      "properties": {
        "barCode": {
          "type": "string"
        },
        "confirmedDlv": {
          "type": "string"
        },
        "currencyCode": {
          "type": "string"
        },
        "deliveryDate": {
          "type": "string",
          "format": "date-time"
        },
        "discPercent": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "documentDate": {
          "type": "string",
          "format": "date-time"
        },
        "documentNum": {
          "type": "string"
        },
        "fileData": {
          "type": "string",
          "format": "byte",
          "description": "Base64 encoded document. Accepts PDF, MSG, TIFF, JPG."
        },
        "fXLImportId": {
          "type": "string"
        },
        "fXLWorkerPurchPlacer": {
          "type": "string"
        },
        "gLNCode": {
          "type": "string"
        },
        "invoiceAccount": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "orderAccount": {
          "type": "string"
        },
        "receiptDateRequested": {
          "type": "string"
        },
        "shippingDateRequested": {
          "type": "string"
        },
        "custAccount": {
          "type": "string"
        },
        "purchOrderFormNum": {
          "type": "string"
        },
        "shipComplete": {
          "type": "boolean"
        },
        "customerRef": {
          "type": "string"
        },
        "updateAction": {
          "type": "string"
        },
        "vendorRef": {
          "type": "string"
        },
        "workerPurchPlacer": {
          "type": "string"
        }
      }
    },
    "PurchaseHeader": {
      "type": "object",
      "required": [
        "orderAccount",
        "documentNum"
      ],
      "properties": {
        "barCode": {
          "type": "string"
        },
        "confirmedDlv": {
          "type": "string"
        },
        "currencyCode": {
          "type": "string"
        },
        "deliveryDate": {
          "type": "string",
          "format": "date-time"
        },
        "discPercent": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "documentDate": {
          "type": "string",
          "format": "date-time"
        },
        "documentNum": {
          "type": "string"
        },
        "fXLImportId": {
          "type": "string"
        },
        "fXLWorkerPurchPlacer": {
          "type": "string"
        },
        "gLNCode": {
          "type": "string"
        },
        "invoiceAccount": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "orderAccount": {
          "type": "string"
        },
        "receiptDateRequested": {
          "type": "string"
        },
        "shippingDateRequested": {
          "type": "string"
        },
        "custAccount": {
          "type": "string"
        },
        "purchOrderFormNum": {
          "type": "string"
        },
        "shipComplete": {
          "type": "boolean"
        },
        "customerRef": {
          "type": "string"
        },
        "updateAction": {
          "type": "string"
        },
        "vendorRef": {
          "type": "string"
        },
        "workerPurchPlacer": {
          "type": "string"
        }
      }
    },
    "PurchaseConfirmHeader": {
      "type": "object",
      "required": [
        "orderAccount",
        "documentNum"
      ],
      "properties": {
        "barCode": {
          "type": "string"
        },
        "confirmedDlv": {
          "type": "string"
        },
        "currencyCode": {
          "type": "string"
        },
        "deliveryDate": {
          "type": "string",
          "format": "date-time"
        },
        "discPercent": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "documentDate": {
          "type": "string",
          "format": "date-time"
        },
        "documentNum": {
          "type": "string"
        },
        "fXLImportId": {
          "type": "string"
        },
        "fXLWorkerPurchPlacer": {
          "type": "string"
        },
        "gLNCode": {
          "type": "string"
        },
        "invoiceAccount": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "orderAccount": {
          "type": "string"
        },
        "purchOrderFormNum": {
          "type": "string"
        },
        "shipComplete": {
          "type": "boolean"
        },
        "updateAction": {
          "type": "string"
        },
        "vendorRef": {
          "type": "string"
        },
        "workerPurchPlacer": {
          "type": "string"
        }
      }
    },
    "PurchaseLine": {
      "type": "object",
      "properties": {
        "confirmedDlv": {
          "type": "string"
        },
        "deliveryDate": {
          "type": "string"
        },
        "externalItemId": {
          "type": "string"
        },
        "fxlImportId": {
          "type": "string"
        },
        "globalTradeItemNumber": {
          "type": "string"
        },
        "intrastatCommodity": {
          "type": "string"
        },
        "itemBarCode": {
          "type": "string"
        },
        "itemId": {
          "type": "string"
        },
        "lineNum": {
          "type": "integer",
          "format": "int32"
        },
        "linePercent": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "message": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "origCountryRegionId": {
          "type": "string"
        },
        "port": {
          "type": "string"
        }
      }
    },
    "PurchaseConfirmLine": {
      "type": "object",
      "properties": {
        "confirmedDlv": {
          "type": "string"
        },
        "deliveryDate": {
          "type": "string"
        },
        "externalItemId": {
          "type": "string"
        },
        "fxlImportId": {
          "type": "string"
        },
        "globalTradeItemNumber": {
          "type": "string"
        },
        "intrastatCommodity": {
          "type": "string"
        },
        "itemBarCode": {
          "type": "string"
        },
        "itemId": {
          "type": "string"
        },
        "lineNum": {
          "type": "integer",
          "format": "int32"
        },
        "linePercent": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "message": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "origCountryRegionId": {
          "type": "string"
        },
        "port": {
          "type": "string"
        },
        "priceUnit": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "purchPrice": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "purchQty": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "purchUnit": {
          "type": "string"
        },
        "shipComplete": {
          "type": "string"
        },
        "updateAction": {
          "type": "string"
        }
      }
    },
    "PurchaseInvoiceLine": {
      "type": "object",
      "properties": {
        "confirmedDlv": {
          "type": "string"
        },
        "deliveryDate": {
          "type": "string"
        },
        "externalItemId": {
          "type": "string"
        },
        "fxlImportId": {
          "type": "string"
        },
        "globalTradeItemNumber": {
          "type": "string"
        },
        "intrastatCommodity": {
          "type": "string"
        },
        "itemBarCode": {
          "type": "string"
        },
        "itemId": {
          "type": "string"
        },
        "lineNum": {
          "type": "integer",
          "format": "int32"
        },
        "linePercent": {
          "type": "number",
          "description": "Precision of two digits"
        },
        "message": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "origCountryRegionId": {
          "type": "string"
        },
        "port": {
          "type": "string"
        }
      }
    },
    "CollectionLines": {
      "type": "object",
      "properties": {
        "discAmount": {
          "type": "number"
        },
        "documentDate": {
          "type": "string",
          "format": "date-time"
        },
        "grossAmount": {
          "type": "number"
        },
        "message": {
          "type": "string"
        },
        "netAmount": {
          "type": "number"
        },
        "paymAmount": {
          "type": "number"
        },
        "paymentReference": {
          "type": "string"
        },
        "paymentReferenceType": {
          "type": "string"
        }
      }
    },
    "BvbsImport": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "lines": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/BvbsLine"
              }
            }
          }
        }
      },
      "example": {
        "_contract": {
          "message": {
            "companyId": "usmf",
            "fromSystem": "Azure Integration",
            "description": "Test Integration",
            "applicationId": "BVBS"
          },
          "lines": {
            "BOMItemId": "bi1234-56789",
            "FileName": "test_bvbs_input_file.bvbs",
            "Geometrie": "l10w10l10w10",
            "Length": 10,
            "MeshType": "Q188",
            "PlanId": "04321",
            "PositionNo": "1",
            "ProjectId": "pbi2219",
            "Qty": 1,
            "Quality": "B500",
            "ReinforcementType": "Rod",
            "RodDiameter": 10,
            "RollDiameter": 10,
            "Weight": 10.123456,
            "Width": 10
          }
        }
      }
    },
    "BvbsLine": {
      "type": "object",
      "properties": {
        "BOMItemId": {
          "type": "string"
        },
        "FileName": {
          "type": "string"
        },
        "Geometrie": {
          "type": "string"
        },
        "Length": {
          "type": "integer",
          "format": "int32"
        },
        "MeshType": {
          "type": "string"
        },
        "PlanId": {
          "type": "string"
        },
        "PositionNo": {
          "type": "string"
        },
        "ProjectId": {
          "type": "string"
        },
        "Qty": {
          "type": "integer",
          "format": "int32"
        },
        "Quality": {
          "type": "string"
        },
        "ReinforcementType": {
          "type": "string"
        },
        "RodDiameter": {
          "type": "integer",
          "format": "int32"
        },
        "RollDiameter": {
          "type": "integer",
          "format": "int32"
        },
        "Weight": {
          "type": "number",
          "description": "Precision of six digits."
        },
        "Width": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "ProductionStart": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "message": {
              "$ref": "#/definitions/Message"
            },
            "prodId": {
              "type": "string"
            }
          }
        }
      },
      "example": {
        "_contract": {
          "message": {
            "applicationId": "ProdSystem",
            "companyId": "usmf",
            "description": "Production start message",
            "messageId": "abcd-1234-efgh-5678",
            "messageTimeStamp": "YYYY-MM-DDTHH:mm:ss"
          },
          "prodId": "usmf-000027349"
        }
      }
    },
    "ProductionFinished": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "endjob": {
              "type": "boolean",
              "description": "true for Completed, false for Progress"
            },
            "inventLocationId": {
              "type": "string"
            },
            "itemId": {
              "type": "string"
            },
            "message": {
              "$ref": "#/definitions/Message"
            },
            "processingTime": {
              "type": "number",
              "description": "Precision of two digits. Unit defined in D365."
            },
            "prodId": {
              "type": "string"
            },
            "qtyError": {
              "type": "number",
              "description": "Precision of two digits."
            },
            "qtyGood": {
              "type": "number",
              "description": "Precision of two digits."
            }
          }
        }
      },
      "example": {
        "_contract": {
          "endJob": true,
          "inventLocationId": "0001",
          "itemId": "056-S",
          "message": {
            "applicationId": "ProdSystem",
            "companyId": "usmf",
            "description": "Production start message",
            "messageId": "abcd-1234-efgh-5678",
            "messageTimeStamp": "YYYY-MM-DDTHH:mm:ss"
          },
          "processingTime": 0,
          "prodId": "usmf-000027349",
          "qtyError": 0,
          "qtyGood": 1
        }
      }
    },
    "ProductionProgress": {
      "type": "object",
      "properties": {
        "_contract": {
          "type": "object",
          "properties": {
            "endjob": {
              "type": "boolean",
              "description": "true for Completed, false for Progress"
            },
            "inventLocationId": {
              "type": "string"
            },
            "itemId": {
              "type": "string"
            },
            "message": {
              "$ref": "#/definitions/Message"
            },
            "processingTime": {
              "type": "number",
              "description": "Precision of two digits. Unit defined in D365."
            },
            "prodId": {
              "type": "string"
            },
            "qtyError": {
              "type": "number",
              "description": "Precision of two digits."
            },
            "qtyGood": {
              "type": "number",
              "description": "Precision of two digits."
            },
            "resource": {
              "type": "string"
            },
            "timestampFinished": {
              "type": "string",
              "format": "date-time"
            },
            "timestampStarted": {
              "type": "string",
              "format": "date-time"
            }
          },
          "example": {
            "_contract": {
              "endJob": false,
              "inventLocationId": "001",
              "itemId": "056-S",
              "message": {
                "applicationId": "ProdSystem",
                "companyId": "usmf",
                "description": "Production start message",
                "messageId": "abcd-1234-efgh-5678",
                "messageTimeStamp": "YYYY-MM-DDTHH:mm:ss"
              },
              "processingTime": 181,
              "prodId": "usmf-000027349",
              "qtyError": 0,
              "qtyGood": 1,
              "resource": "MB-4 resource",
              "timestampFinished": "2024-07-12T06:19:01.0440Z",
              "timestampStarted": "2024-07-12T06:16:00.0010Z"
            }
          }
        }
      }
    },
    "ItemArrivalCreate": {
      "type": "object",
      "properties": {
        "message": {
          "$ref": "#/definitions/Message"
        },
        "header": {
          "$ref": "#/definitions/ItemArrivalHeader"
        },
        "lines": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ItemArrivalLines"
          }
        }
      }
    },
    "ItemArrivalHeader": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "inventTransRefId": {
          "type": "string"
        },
        "inventTransType": {
          "type": "string",
          "description": "Use Purch as value"
        },
        "journalId": {
          "type": "string"
        },
        "journalNameId": {
          "type": "string"
        },
        "packingSlipId": {
          "type": "string"
        }
      }
    },
    "ItemArrivalLines": {
      "type": "object",
      "properties": {
        "inventBatchExpDate": {
          "type": "string",
          "format": "date-time"
        },
        "inventBatchId": {
          "type": "string"
        },
        "inventLocationId": {
          "type": "string"
        },
        "inventSiteId": {
          "type": "string"
        },
        "inventTransId": {
          "type": "string"
        },
        "itemId": {
          "type": "string"
        },
        "lineNum": {
          "type": "integer",
          "format": "int32"
        },
        "qty": {
          "type": "integer",
          "format": "int32"
        },
        "transDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "PickingListRegistration": {
      "type": "object",
      "properties": {
        "message": {
          "$ref": "#/definitions/Message"
        },
        "header": {
          "$ref": "#/definitions/PickingListRegistrationHeader"
        },
        "lines": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PickingListRegistrationLines"
          }
        }
      }
    },
    "PickingListRegistrationHeader": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "inventTransRefId": {
          "type": "string"
        },
        "inventTransType": {
          "type": "string"
        },
        "journalId": {
          "type": "string"
        },
        "journalNameId": {
          "type": "string"
        },
        "packingSlipId": {
          "type": "string"
        }
      }
    },
    "PickingListRegistrationLines": {
      "type": "object",
      "properties": {
        "inventBatchId": {
          "type": "string"
        },
        "inventLocationId": {
          "type": "string"
        },
        "inventSiteId": {
          "type": "string"
        },
        "inventTransId": {
          "type": "string"
        },
        "itemId": {
          "type": "string"
        },
        "lineNum": {
          "type": "integer",
          "format": "int32"
        },
        "qty": {
          "type": "integer",
          "format": "int32"
        },
        "transDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "Line": {
      "type": "object",
      "properties": {
        "lineNum": {
          "type": "integer",
          "format": "int32"
        },
        "itemId": {
          "type": "string"
        },
        "salesPrice": {
          "type": "string"
        },
        "salesQty": {
          "type": "string"
        },
        "salesUnit": {
          "type": "string"
        },
        "itemBarCode": {
          "type": "string"
        },
        "globalTradeItemNumber": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "ApiResponse": {
      "type": "object",
      "properties": {
        "$id": {
          "type": "integer",
          "format": "int32"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "jobId": {
          "type": "string"
        },
        "jobStatus": {
          "type": "integer",
          "format": "int32"
        },
        "jobMessage": {
          "type": "string"
        }
      },
      "example": {
        "$id": "1",
        "status": "200",
        "jobId": "2023-06-09T12:59:49-0DABEE0293684C87B2E1B2D7AA65E770",
        "jobStatus": "2",
        "JobMessage": "Job '2023-06-09T12:59:49-0DABEE0293684C87B2E1B2D7AA65E770' has been processed succesfully."
      }
    },
    "Api400Response": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        },
        "ExceptionType": {
          "type": "string"
        },
        "ActivityId": {
          "type": "string"
        }
      },
      "example": {
        "Message": "An exception occured when deserializing the request - Exception occurred when parsing and deserializing parameter '_contract' - 'Parameter '_contract' is not found within the request content body.",
        "ExceptionType": "XppServicesDeserializationException",
        "ActivityId": "15eeee57-9ac2-0001-4325-ef15c29ad901"
      }
    }
  },
  "externalDocs": {
    "description": "Find out more about FlexxWare",
    "url": "https://soluvine.com/products"
  }
}